-- Seed interests for matching
INSERT INTO public.interests (name, category) VALUES
  -- Music
  ('Pop', 'music'),
  ('Hip Hop', 'music'),
  ('R&B', 'music'),
  ('Rock', 'music'),
  ('Indie', 'music'),
  ('Electronic', 'music'),
  ('Jazz', 'music'),
  ('Classical', 'music'),
  ('Country', 'music'),
  ('K-Pop', 'music'),
  -- Movies
  ('Comedy', 'movies'),
  ('Drama', 'movies'),
  ('Action', 'movies'),
  ('Horror', 'movies'),
  ('Romance', 'movies'),
  ('Sci-Fi', 'movies'),
  ('Documentary', 'movies'),
  ('Anime', 'movies'),
  ('Thriller', 'movies'),
  ('Fantasy', 'movies'),
  -- Hobbies
  ('Reading', 'hobbies'),
  ('Gaming', 'hobbies'),
  ('Cooking', 'hobbies'),
  ('Hiking', 'hobbies'),
  ('Photography', 'hobbies'),
  ('Art', 'hobbies'),
  ('Music', 'hobbies'),
  ('Sports', 'hobbies'),
  ('Travel', 'hobbies'),
  ('Fitness', 'hobbies'),
  ('Yoga', 'hobbies'),
  ('Dancing', 'hobbies'),
  -- Personality
  ('Introvert', 'personality'),
  ('Extrovert', 'personality'),
  ('Ambivert', 'personality'),
  ('Night Owl', 'personality'),
  ('Early Bird', 'personality'),
  ('Adventurous', 'personality'),
  ('Homebody', 'personality'),
  ('Creative', 'personality'),
  -- Lifestyle
  ('Vegetarian', 'lifestyle'),
  ('Vegan', 'lifestyle'),
  ('Foodie', 'lifestyle'),
  ('Pet Lover', 'lifestyle'),
  ('Dog Person', 'lifestyle'),
  ('Cat Person', 'lifestyle'),
  ('Coffee Addict', 'lifestyle'),
  ('Tea Lover', 'lifestyle'),
  ('Minimalist', 'lifestyle'),
  ('Sustainability', 'lifestyle')
ON CONFLICT (name) DO NOTHING;
